name: CI Java

on:
  workflow_call:

jobs: 

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '11'
        distribution: 'zulu'
    
    - name: Compile Gradle
      run: |
        chmod +x gradlew
        ./gradlew build

    - name: Validacion Jar
      run: | 
        ls -lt
        ls -lt $GITHUB_WORKSPACE/build/libs

    - name: Copia de Jar a Raiz 
      run: |
        cp $GITHUB_WORKSPACE/build/libs/spring-petclinic-2.6.0.jar .
        chmod 777 spring-petclinic-2.6.0.jar
        ls -lt 
    
    - name: Analisis SonarCloud
      run: |
        chmod +x gradlew 
        #./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD }}

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build 
      run: | 
        docker build --tag clagosu/pet-clinic:latest .
        docker images

    - name: Docker Push
      run : |
        docker push clagosu/pet-clinic
  deploy: 
    needs: build
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Deploy Kubernetes
      run: |
        kubectl apply -f $GITHUB_WORKSPACE/deploy/deployment.yaml
  

         

        

    
    
    
